### ISSUE TITLE
Clicking on ports  redirects to nowhere 

### ISSUE THREAD

**Issue by mosn** [arcticicestudio/nord-docs#154]
> Related issues:

## Description

Describe the bug as in many relevant details as possible with a clear and concise description. Ensure to fill in the [steps to reproduce](#steps-to-reproduce) it.

### Steps to Reproduce

1. Visit ports 
2. Click on any port

### Expected Behavior
What do you expect to happen?
Redirect and show README markdown

### Actual Behavior

What actually happens?
https://dsc.cloud/b79a50/U8rTbgBOXPsQwaIXq1sEh32H0G2hDbMVZweKxIG5pKBJok2P1CGkL7OEBPZdGFiCHlOZHxvef2Or4C59BrITerh5S8HO7QNqIDNC.png

Issue persists after update/upgrade

**Comment by mosn** [comment]
Having spent some time, It appears that this is related to transition and WIP. Please feel free to close if that is the case

**Comment by arcticicestudio** [comment]
Hi @mosn :wave:, thanks for your contribution :+1:
Most port projects are still in transition so there is no dedicated page for them yet. They are all moved one-by-one if my free time allows it.
Some port projects like [JetBrains][jb], [Visual Studio Code][vscode], [Vim][] or [tmux][] are already ported so you can see how the pages of other ports might look like later on.

In the meantime, like advised on the placeholder pages, please visit the repository linked in the description of the specific port project to get to know more about it as well as getting information about the installation and setup.

[vscode]: https://www.nordtheme.com/ports/visual-studio-code
[tmux]: https://www.nordtheme.com/ports/tmux
[jb]: https://www.nordtheme.com/ports/jetbrains
[vim]: https://www.nordtheme.com/ports/vim

**Comment by mosn** [comment]
@arcticicestudio are there specific required steps for each transition or is it general moving things from one place to another. As it turns out I might have some time that I can contribute here. Maybe point us to a PR or other resource that can get us up to speed and we'll get started.

**Comment by arcticicestudio** [comment]
Currently most of the work for the transitions are collecting the information, designing and implementing the landing page, creating assets, rewriting and import all docs and finally refactor and clean up the port project repository. Since all ports for terminal themes will use common/shared page components (projects only provide colors so there's no real difference other than the target application) there are only some ports left that require individual designs.

If you like to help I'm happy about any contribution in the port project repositories regarding open issues, requested features or long-time outstanding implementations and bug fixes. Since I try to finish the transitions first there is not much time left to actively maintain the ports at the moment so I really appreciate every help there :smile:

**Comment by mosn** [comment]
Hey @arcticicestudio Thank your the tip and information provided. I just realized that the topic I picked, was exactly one with no porting issue at all. 😅I needed to work on that for my own project and though to share findings here as well... But I am going to pick one from the port issues and get started.  If you have a preference please let me know.🙏
