### ISSUE TITLE
Content delivery system Integration for landing

### ISSUE THREAD

**Issue by bindlr** [arcticicestudio/nord-docs#156]
> Related issues:
#129 #144 

## Description
This issue is to discover whether there's a need to integrate MDX for landing pages. If this is indeed in the roadmap, we can allocate resource to it as we are at a position where we have to decide whether Landing Pages remains as is or it's safer to switch to MDX. 

One possible reason for keeping things the way they are currently, might be the way the Landing Page have been setup. I understand the efficiency and ease of use of existing setup. However, components and UI elements that are used are almost exclusively used for Nord project and they might not provide proper brand identity for other project. Therefore a suggestion can be to either

a. Integration with CMS system to serve dynamic content as seen in Blog and Docs pages.
b. Define a mechanism that assets in the project can be easily replaced. Ideally better api for animations. etc..

**Comment by mosn** [comment]
I was able to take a better look at this case. I believe following approach could work. ( Appreciate feedback from authors)

Instead of integrating MDX for landing page, which now I believe is over engineering things, we can use Netlify CMS to distribute the landing page content and assets. 

This approach could also work with how landing page setup has been laid out and provides a user friendly interface to swap and customize asset. 

I also noticed that Netlify is already supporting CI/CD pipeline and that's another reason for my conclusion. 

To have matter in motion, I went ahead and implemented above scenario and can confirm feasibility of this approach. 

There is one unclear part and thats the current custom layout of the landing page and how we can convert it to a Netlify CMS collection. Is it going to be a single collection with multiple fields that eventually form a unified page or shall I consider each section as a page and find a way to “stick it” together at some point.

**Comment by bindlr** [comment]
The reason for which we opened this issue has changed now. It is now more about find a content delivery system mechanism for the landing page. Still looking forward to Authors response if the repo is actively being maintained

**Comment by bindlr** [comment]
For anyone arriving here with the same question, I solved this issue by issuing [styled-jsx](https://github.com/zeit/styled-jsx) It also helped with templating but since this is not at all inline with upstream, I won't send request a pull for it. I will share the link here soon.
