### ISSUE TITLE
Broken links to articicestudio.com and svengreb.de in the footer

### ISSUE THREAD

**Issue by HiranmayaGundu** [arcticicestudio/nord-docs#193]
## Prerequisites

- [x] **Ensure the bug has not already been reported by using the [GitHub Issues search](https://github.com/arcticicestudio/nord-docs/issues)*
- [x] **Ensure your contribution belongs to the correct [main or port project repository](https://github.com/arcticicestudio?&tab=repositories&q=nord).**
- [x]  **Ensure the bug is reproducible and has not already been fixed** — use the [latest version](https://github.com/arcticicestudio/nord-docs/releases/latest) and [`develop`](https://github.com/arcticicestudio/nord-docs/tree/develop) branch.

## Description

A heads up that the two links in the footer lead to the default 404 not found page.  Love the docs website and learning a lot from the animations, thanks for making it open source! 

### Steps to Reproduce

1. Click on the links in the footer

### Expected Behavior

It takes you to the functional relevant websites.

### Actual Behavior

Leads you to broken websites. 

## Environment and Versions

Running on windows and using Chromium Edge, though I doubt that makes a difference.

**Comment by arcticicestudio** [comment]
Hi @HiranmayaGundu :wave:, thanks for your contribution :+1:
Nice to see you like the project!

The links are broken due to the fact that both the _Arctic Ice Studio_ and my personal (Sven Greb) websites are still large items on "get it done" list, but unfortunately my days of have 24 hours 😄 
I've already added them to the footer to ensure reference backtracking but also so I don't have to update the site when I deploy both sites to the public.
Maybe I'll find some time to set up minimal (placeholder) sites so that the 404 are gone, but at the moment there are a lot of other important tasks. Thanks for your report anyway 👍

**Comment by HiranmayaGundu** [comment]
Ah okay! Thanks for your work 😁
